### ISSUE TITLE
meteor publish-for-arch

### ISSUE THREAD

**Issue by kandizzy** [acidsound/meteor-mqtt#1]
Hi there, 

Would you be able to publish this for Ubuntu? Alternatively, if you add me as a maintainer I can do it- I have a machine set up for it. Let me know, thanks!

**Comment by kandizzy** [comment]
Made a fork to solve my issue.

**Comment by acidsound** [comment]
@kandizzy Today, I published this package for Ubuntu x86/x64/Windows. please check this out :+1:
